export default {
  products: [
    {
      _id: 1,
      name: 'Linenmix Shortsleeve Shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/sndct_shirt_300421_site_3_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/_DSC6795-Edit-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/sndct_shirt_300421_site_3_2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 25,
      color: 'beige',
      rating: 4.5,
      numReviews: 5,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      _id: 2,
      name: 'Linenmix Shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/sndct_shirt_0905421_site_4_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/_DSC6881-Edit-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/shirts/sndct_shirt_0905421_site_4_3-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 32,
      color: 'beige',
      rating: 5,
      numReviews: 2,
      isOnSale: true,
      isNewArrival: false,
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      _id: 3,
      name: 'Virgin Wool Shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20fw21/shirts/sndct_shirt_141021_site_1_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/shirts/sndct_0559-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/shirts/sndct_shirt_141021_site_1_2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 30,
      color: 'dark beige',
      rating: 4.5,
      numReviews: 1,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      _id: 4,
      name: 'Jersey Regular T-shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/White_regular_tee-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/White_regular_tee-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/White_regular_tee2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 18,
      color: 'white',
      rating: 4.5,
      numReviews: 1,
      isOnSale: true,
      isNewArrival: false,
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      _id: 5,
      name: 'Shadow 600 Saucony Creek',
      category: 'shoes',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70672-1_1-600x600-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70672-1_2-1000x1000-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70672-1_5-1000x1000-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 99,
      color: 'white',
      rating: 5,
      numReviews: 5,
      isOnSale: false,
      isNewArrival: true,
    },
    {
      _id: 6,
      name: 'Saucony Endorphin Trail',
      category: 'shoes',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S20716-50_1-600x600-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S20716-50_2-1000x1000-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S20716-50_5-1000x1000-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 110,
      color: 'yellow',
      rating: 5,
      numReviews: 2,
      isOnSale: true,
      isNewArrival: false,
    },
    {
      _id: 7,
      name: 'Grid Web',
      category: 'shoes',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70649-1_1-600x600-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70649-1_2-1000x1000-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/sneakers/S70649-1_5-1000x1000-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 150,
      color: 'black',
      rating: 4.5,
      numReviews: 1,
      isOnSale: false,
      isNewArrival: false,
    },
    {
      _id: 8,
      name: 'Trainer Hoodie',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/Faded/Hoodie/Faded_hoodie_blue1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/Faded/Hoodie/Faded_hoodie_blue2-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/Faded/Hoodie/Faded_hoodie_blue-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 18,
      color: 'blue',
      rating: 4,
      numReviews: 4,
      isOnSale: false,
      isNewArrival: false,
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      _id: 9,
      name: '4 Panel Bucket Hat',
      category: 'accessories',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20ss21/bucket%20hats/photo_2021-07-15%2015.10.01-840x1060.jpeg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/bucket%20hats/sndct_bucket%20hat_260621_site_1_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/bucket%20hats/sndct_bucket%20hat_260621_site_1_2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 15,
      color: 'green',
      rating: 5,
      numReviews: 2,
      isOnSale: false,
      isNewArrival: true,
    },
    {
      _id: 10,
      name: '6-Panel Trainer Cap',
      category: 'accessories',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/violet-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/Cap_Violet_site_post%20copy-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/violet2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      price: 17,
      color: 'purple',
      rating: 5,
      numReviews: 2,
      isOnSale: false,
      isNewArrival: true,
    },
    {
      _id: 11,
      name: '6-Panel Trainer Cap',
      category: 'accessories',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/Blue-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/Cap_Blue_post-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/Blue2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'blue',
      price: 17,
      rating: 4.5,
      numReviews: 4,
      isOnSale: false,
      isNewArrival: true,
    },
    {
      _id: 12,
      name: '6-Panel Trainer Cap',
      category: 'accessories',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20ss21/caps/sndct_cap_03521_site_5_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/caps/Cap_Black_site_post-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20ss21/caps/sndct_cap_03521_site_5_2-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'black',
      price: 17,
      rating: 4.5,
      numReviews: 4,
      isOnSale: false,
      isNewArrival: true,
    },
    {
      _id: 13,
      name: 'Heavyweight Jersey Regular T-shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/Beige_Regular-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/Beige_Regular1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/t-shirts/flamli%20regular/Beige_Regula_details-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'beige',
      price: 20,
      rating: 4,
      numReviews: 2,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['S', 'M'],
    },
    {
      _id: 14,
      name: 'Trainer Pants',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/Pants/Sweatpants_beige1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/Pants/Sweatpants_beige2-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/Pants/Sweatpants_beige-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'beige',
      price: 20,
      rating: 4,
      numReviews: 2,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['M', 'L'],
    },
    {
      _id: 15,
      name: 'Tank Top',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/tanks/Site_post_template%D0%BC%D0%B0%D0%B8%CC%86%D0%BA%D0%B01-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/tanks/Site_post_template12.02.220021-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/tanks/Site_post_template12.02.220023-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'grey',
      price: 15,
      rating: 4.5,
      numReviews: 0,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['M', 'L'],
    },
    {
      _id: 19,
      name: 'Trainer Shorts',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collections%20ss22/shorts/Shorts_beige2-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/shorts/Shorts_beige-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collections%20ss22/shorts/Shorts_beige3-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'beige',
      price: 15,
      rating: 4.5,
      numReviews: 0,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['M', 'L'],
    },
    {
      _id: 20,
      name: 'Regular T-shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_t-shirt_150921_site_13_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_0205-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_0208-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'gren',
      price: 20,
      rating: 4.5,
      numReviews: 0,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['S', 'M', 'L'],
    },
    {
      _id: 21,
      name: 'Regular T-shirt',
      category: 'fashion',
      images: [
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_t-shirt_150921_site_10_1-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_0372-840x1060.jpg',
        'https://www.sndct.com/image/cache/data/collection%20fw21/t-shirts/regular/sndct_0370-840x1060.jpg',
      ],
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iure, dolorem quam recusandae aperiam eveniet?`,
      color: 'red',
      price: 20,
      rating: 4.5,
      numReviews: 0,
      isOnSale: false,
      isNewArrival: true,
      sizes: ['S', 'M', 'L'],
    },
  ],
};
